# Generated by Django 5.1.2 on 2024-11-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('retired', 'Retired')], default='pending', max_length=20)),
                ('id_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.pagos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.firebaseuser')),
            ],
        ),
    ]
