# Generated by Django 5.1.2 on 2024-10-18 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('s3_url', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_procesamiento', models.CharField(default='pendiente', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firebaseuser')),
            ],
        ),
    ]
