# Generated by Django 5.1.2 on 2024-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_firebaseuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firebaseuser',
            options={'verbose_name': 'Firebase User'},
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
