# Generated by Django 5.1.2 on 2024-10-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=255)),
                ('id_destino', models.ManyToManyField(related_name='notificaciones_destino', to='core.firebaseuser')),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_origen', to='core.firebaseuser')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuarios', models.ManyToManyField(to='core.firebaseuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('id_archivos', models.ManyToManyField(to='core.archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firebaseuser')),
            ],
        ),
    ]
