# Generated by Django 5.1.2 on 2024-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_firebaseuser_options_firebaseuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
