# Generated by Django 5.1.2 on 2024-11-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_firebaseuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='id_archivos',
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField()),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firebaseuser')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carga'),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firebaseuser')),
            ],
        ),
        migrations.AddField(
            model_name='carga',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pagos'),
        ),
        migrations.CreateModel(
            name='TramiteFileRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.archivo')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_file_requirements', to='core.tramite')),
            ],
        ),
    ]
