# Generated by Django 5.1.2 on 2024-11-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_filetype_remove_tramitefilerequirement_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='usuario',
        ),
        migrations.AddField(
            model_name='carga',
            name='localizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='usuario_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tramites_destino', to='core.firebaseuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramite',
            name='usuario_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tramites_origen', to='core.firebaseuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carga',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('retired', 'Retired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='carga',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='id_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pagos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramitefilerequirement',
            name='status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
