# Generated by Django 5.1.2 on 2024-11-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tramite_usuario_carga_localizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tramite',
            name='tramite_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tramitetype'),
            preserve_default=False,
        ),
    ]
