# Generated by Django 5.1.2 on 2024-11-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('s3_url', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_procesamiento', models.CharField(default='pendiente', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.firebaseuser')),
            ],
        ),
        migrations.CreateModel(
            name='TramiteFileRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.archivo')),
                ('tipo_archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.filetype')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_file_requirements', to='tramites.tramite')),
            ],
        ),
    ]
