# Generated by Django 5.1.2 on 2024-11-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('not_seen', 'Not Seen'), ('seen', 'Seen')], default='pending', max_length=20)),
                ('id_destino', models.ManyToManyField(related_name='notificaciones_destino', to='users.firebaseuser')),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_origen', to='users.firebaseuser')),
            ],
        ),
    ]
