# Generated by Django 5.1.2 on 2024-11-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargas.carga')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_destino', to='users.firebaseuser')),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_origen', to='users.firebaseuser')),
                ('tramite_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramitetype')),
            ],
        ),
    ]
